apiVersion: v1
kind: ConfigMap
metadata:
  name: openapp-config
  namespace: openapp-system
data:
  registry: |
    https://github.com/openapp-dev/openapp-registry@main
  username: "openapp"
  password: "openapp"
