---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openapp-controller
  namespace: openapp-system
  labels:
    app.kubernetes.io/component: openapp-controller
    app.kubernetes.io/name: openapp
    app.kubernetes.io/version: devel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openapp-controller
  template:
    metadata:
      labels:
        app: openapp-controller
        app.kubernetes.io/component: openapp-controller
        app.kubernetes.io/name: openapp
        app.kubernetes.io/version: devel
    spec:
      hostNetwork: true
      serviceAccountName: openapp-sa
      securityContext:
        runAsUser: 0
      volumes:
        - name: openapp
          hostPath:
            path: /root/openapp
            type: DirectoryOrCreate
      containers:
        - name: openapp-controller
          # This is the Go import path for the binary that is containerized
          # and substituted here.
          image: ko://github.com/openapp-dev/openapp/cmd/controller
          args:
            - --v=4
          volumeMounts:
            - name: openapp
              mountPath: /root/openapp
          env:
            - name: LOCAL_IP
              value: "localhost"
      terminationGracePeriodSeconds: 30
