---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openapp-apiserver
  namespace: openapp-system
  labels:
    app.kubernetes.io/component: openapp-apiserver
    app.kubernetes.io/name: openapp
    app.kubernetes.io/version: devel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openapp-apiserver
  template:
    metadata:
      labels:
        app: openapp-apiserver
        app.kubernetes.io/component: openapp-apiserver
        app.kubernetes.io/name: openapp
        app.kubernetes.io/version: devel
    spec:
      serviceAccountName: openapp-sa
      containers:
        - name: openapp-apiserver
          # This is the Go import path for the binary that is containerized
          # and substituted here.
          image: ko://github.com/openapp-dev/openapp/cmd/apiserver
          args:
            - --v=4
          ports:
            - name: server
              containerPort: 8080
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: openapp
  namespace: openapp-system
  labels:
    app: openapp-apiserver
    app.kubernetes.io/component: openapp-apiserver
    app.kubernetes.io/version: devel
    app.kubernetes.io/name: openapp
spec:
  selector:
    app: openapp-apiserver
  ports:
    - name: openapp
      port: 8080
      targetPort: 8080
      nodePort: 30003
  type: NodePort
