---
# Copyright 2024 The OpenAPP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: openapp-controller
  namespace: openapp-system
  labels:
    app.kubernetes.io/component: openapp-controller
    app.kubernetes.io/name: openapp
    app.kubernetes.io/version: devel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openapp-controller
  template:
    metadata:
      labels:
        app: openapp-controller
        app.kubernetes.io/component: openapp-controller
        app.kubernetes.io/name: openapp
        app.kubernetes.io/version: devel
    spec:
      hostNetwork: true
      serviceAccountName: openapp-sa
      securityContext:
        runAsUser: 0
      volumes:
        - name: openapp
          hostPath:
            path: /root/openapp
            type: DirectoryOrCreate
      containers:
        - name: openapp-controller
          # This is the Go import path for the binary that is containerized
          # and substituted here.
          image: ko://github.com/openapp-dev/openapp/cmd/controller
          args:
            - --v=4
          volumeMounts:
            - name: openapp
              mountPath: /root/openapp
          env:
            - name: LOCAL_IP
              value: "localhost"
      terminationGracePeriodSeconds: 30
