---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openapp-sa
  namespace: openapp-system
  labels:
    app.kubernetes.io/name: openapp
    app.kubernetes.io/version: devel

---
# The gateway app component needs the serviceaccount to operate the corresponding resources.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openapp-sa
  namespace: openapp
  labels:
    app.kubernetes.io/name: openapp
    app.kubernetes.io/version: devel

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openapp-cluster-rb
  labels:
    app.kubernetes.io/name: openapp
    app.kubernetes.io/version: devel
subjects:
  - kind: ServiceAccount
    name: openapp-sa
    namespace: openapp-system
  - kind: ServiceAccount
    name: openapp-sa
    namespace: openapp
roleRef:
  kind: ClusterRole
  name: openapp-cluster-role
  apiGroup: rbac.authorization.k8s.io
