//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 The OpenAPP Authors.
SPDX-License-Identifier: BUSL-1.1
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/openapp-dev/openapp/pkg/apis/common/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicServiceInstance) DeepCopyInto(out *PublicServiceInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicServiceInstance.
func (in *PublicServiceInstance) DeepCopy() *PublicServiceInstance {
	if in == nil {
		return nil
	}
	out := new(PublicServiceInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PublicServiceInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicServiceInstanceList) DeepCopyInto(out *PublicServiceInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PublicServiceInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicServiceInstanceList.
func (in *PublicServiceInstanceList) DeepCopy() *PublicServiceInstanceList {
	if in == nil {
		return nil
	}
	out := new(PublicServiceInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PublicServiceInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicServiceInstanceSpec) DeepCopyInto(out *PublicServiceInstanceSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicServiceInstanceSpec.
func (in *PublicServiceInstanceSpec) DeepCopy() *PublicServiceInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(PublicServiceInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicServiceInstanceStatus) DeepCopyInto(out *PublicServiceInstanceStatus) {
	*out = *in
	if in.DerivedResources != nil {
		in, out := &in.DerivedResources, &out.DerivedResources
		*out = make([]commonv1alpha1.DerivedResource, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicServiceInstanceStatus.
func (in *PublicServiceInstanceStatus) DeepCopy() *PublicServiceInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(PublicServiceInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicServiceTemplate) DeepCopyInto(out *PublicServiceTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicServiceTemplate.
func (in *PublicServiceTemplate) DeepCopy() *PublicServiceTemplate {
	if in == nil {
		return nil
	}
	out := new(PublicServiceTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PublicServiceTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicServiceTemplateList) DeepCopyInto(out *PublicServiceTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PublicServiceTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicServiceTemplateList.
func (in *PublicServiceTemplateList) DeepCopy() *PublicServiceTemplateList {
	if in == nil {
		return nil
	}
	out := new(PublicServiceTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PublicServiceTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicServiceTemplateSpec) DeepCopyInto(out *PublicServiceTemplateSpec) {
	*out = *in
	if in.ExposeTypes != nil {
		in, out := &in.ExposeTypes, &out.ExposeTypes
		*out = make([]commonv1alpha1.ExposeType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicServiceTemplateSpec.
func (in *PublicServiceTemplateSpec) DeepCopy() *PublicServiceTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(PublicServiceTemplateSpec)
	in.DeepCopyInto(out)
	return out
}
