name: OpenAPP style check

on:
  # pull_request:
  #   branches: [ "main", "release-*" ]
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Check files
        run: |
          ls -alh
          pwd

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          working-directory: /home/runner/work/openapp/openapp
