name: OpenAPP deploy test

on:
  pull_request:
    branches: [ 'main', 'release-*' ]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v3

    - name: Set Up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up a local registry
      run: |
        set -x

        docker run -d -p 5000:5000 --name registry registry:2.7

    - name: Deploy test
      run: |
        set -x

        export K3S_LOG_PATH=~/k3s.log
        export K3S_KUBECONFIG_OUTPUT=~/.k3s-config.yaml
        export KO_DOCKER_REPO=localhost:5000
        hack/local-start.sh

        # sleep 60 seconds to wait the openapp repository to be ready
        sleep 60

        export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
        kubectl get apptemplate -A
